name: GitHub Page Deploy

on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo
        run:  hugo --minify --theme="hyde" --baseUrl="https://rwkey.com/"

      - name: Deploy Hugo to master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master 
          publish_dir: ./public
          force_orphan: true

